import { deepMatch, getSafe, getConfigs, weaveQuery } from './utils';

const uuid = require('uuid');
const fs = require('fs');

class Page {
	/**
	 * @param data: data generated by an instance of DataModel that is to be used in the file created by this page
	 * @param pattern: a Pattern that this page is associated with
	 * @param containerId: id of PageContainer instance that contains this page
	 */
	constructor(data, pattern, containerId) {
		this.context = data;
		this.pattern = pattern;
		this.pageContainer = containerId;
		this.contextHasChanged = true;

		this._id = uuid();

		// TODO: create file
	}

	/**
	 * @param data: data generated by an instance of DataModel
	 * @return old data
	 */
	recomputeData(data) {
		if (data == this.context || deepMatch(data, this.context))
			return data;
		const old = this.context;
		this.context = data;
		this.contextHasChanged = true;
		return old;
	}

	/**
	 * @return id of this page
	 */
	getId() {
		return this._id;
	}

	/**
	 * @return ID of PageContainer instance containing this object
	 */
	getContainerId() {
		return this.pageContainer;
	}

	/**
	 * get the file path associated with this object instance
	 * if context has changed, update the file before returning path
	 * @return path to file associated with this page
	 */
	getFile() {
		let filePath = getSafe(getConfigs(), 'general.pageStorePath');
		if (!filePath) throw new Error('page store directory has not been configured');
		filePath += this.getId() + ".html";
		if (this.contextHasChanged || fs.existsSync(filePath)) {
			let template = weaveQuery('PageContainer', this.getContainerId()).getTemplate();
			// TODO: load in data to filePath using cheerio
			// TODO: write file
			this.contextHasChanged = false;
		};

		return filePath;
	}
}